# Generated by Django 5.2.2 on 2025-06-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, verbose_name='著者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('novel', '小説'), ('business', 'ビジネス'), ('science', '科学'), ('history', '歴史'), ('comic', '漫画'), ('essay', 'エッセイ'), ('other', 'その他')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='comment',
            field=models.TextField(max_length=200, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='おすすめ度'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('reading', '読書中'), ('interested', '興味がある'), ('finished', '読了')], default='reading', max_length=20, verbose_name='読書状況'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='タイトル'),
        ),
    ]
